// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/blog"
	"server/ent/predicate"
	"server/ent/remark"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlogUpdate is the builder for updating Blog entities.
type BlogUpdate struct {
	config
	hooks    []Hook
	mutation *BlogMutation
}

// Where appends a list predicates to the BlogUpdate builder.
func (bu *BlogUpdate) Where(ps ...predicate.Blog) *BlogUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetTitle sets the "title" field.
func (bu *BlogUpdate) SetTitle(s string) *BlogUpdate {
	bu.mutation.SetTitle(s)
	return bu
}

// SetSubtitle sets the "subtitle" field.
func (bu *BlogUpdate) SetSubtitle(s string) *BlogUpdate {
	bu.mutation.SetSubtitle(s)
	return bu
}

// SetTime sets the "time" field.
func (bu *BlogUpdate) SetTime(s string) *BlogUpdate {
	bu.mutation.SetTime(s)
	return bu
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (bu *BlogUpdate) SetNillableTime(s *string) *BlogUpdate {
	if s != nil {
		bu.SetTime(*s)
	}
	return bu
}

// SetCover sets the "cover" field.
func (bu *BlogUpdate) SetCover(s string) *BlogUpdate {
	bu.mutation.SetCover(s)
	return bu
}

// SetHits sets the "hits" field.
func (bu *BlogUpdate) SetHits(i int) *BlogUpdate {
	bu.mutation.ResetHits()
	bu.mutation.SetHits(i)
	return bu
}

// AddHits adds i to the "hits" field.
func (bu *BlogUpdate) AddHits(i int) *BlogUpdate {
	bu.mutation.AddHits(i)
	return bu
}

// SetContentURL sets the "content_url" field.
func (bu *BlogUpdate) SetContentURL(s string) *BlogUpdate {
	bu.mutation.SetContentURL(s)
	return bu
}

// AddRemarkIDs adds the "remarks" edge to the Remark entity by IDs.
func (bu *BlogUpdate) AddRemarkIDs(ids ...int) *BlogUpdate {
	bu.mutation.AddRemarkIDs(ids...)
	return bu
}

// AddRemarks adds the "remarks" edges to the Remark entity.
func (bu *BlogUpdate) AddRemarks(r ...*Remark) *BlogUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return bu.AddRemarkIDs(ids...)
}

// Mutation returns the BlogMutation object of the builder.
func (bu *BlogUpdate) Mutation() *BlogMutation {
	return bu.mutation
}

// ClearRemarks clears all "remarks" edges to the Remark entity.
func (bu *BlogUpdate) ClearRemarks() *BlogUpdate {
	bu.mutation.ClearRemarks()
	return bu
}

// RemoveRemarkIDs removes the "remarks" edge to Remark entities by IDs.
func (bu *BlogUpdate) RemoveRemarkIDs(ids ...int) *BlogUpdate {
	bu.mutation.RemoveRemarkIDs(ids...)
	return bu
}

// RemoveRemarks removes "remarks" edges to Remark entities.
func (bu *BlogUpdate) RemoveRemarks(r ...*Remark) *BlogUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return bu.RemoveRemarkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BlogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BlogUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BlogUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BlogUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BlogUpdate) check() error {
	if v, ok := bu.mutation.Title(); ok {
		if err := blog.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Blog.title": %w`, err)}
		}
	}
	if v, ok := bu.mutation.Subtitle(); ok {
		if err := blog.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "Blog.subtitle": %w`, err)}
		}
	}
	if v, ok := bu.mutation.Hits(); ok {
		if err := blog.HitsValidator(v); err != nil {
			return &ValidationError{Name: "hits", err: fmt.Errorf(`ent: validator failed for field "Blog.hits": %w`, err)}
		}
	}
	if v, ok := bu.mutation.ContentURL(); ok {
		if err := blog.ContentURLValidator(v); err != nil {
			return &ValidationError{Name: "content_url", err: fmt.Errorf(`ent: validator failed for field "Blog.content_url": %w`, err)}
		}
	}
	return nil
}

func (bu *BlogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(blog.Table, blog.Columns, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
	}
	if value, ok := bu.mutation.Subtitle(); ok {
		_spec.SetField(blog.FieldSubtitle, field.TypeString, value)
	}
	if value, ok := bu.mutation.Time(); ok {
		_spec.SetField(blog.FieldTime, field.TypeString, value)
	}
	if value, ok := bu.mutation.Cover(); ok {
		_spec.SetField(blog.FieldCover, field.TypeString, value)
	}
	if value, ok := bu.mutation.Hits(); ok {
		_spec.SetField(blog.FieldHits, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedHits(); ok {
		_spec.AddField(blog.FieldHits, field.TypeInt, value)
	}
	if value, ok := bu.mutation.ContentURL(); ok {
		_spec.SetField(blog.FieldContentURL, field.TypeString, value)
	}
	if bu.mutation.RemarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blog.RemarksTable,
			Columns: []string{blog.RemarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedRemarksIDs(); len(nodes) > 0 && !bu.mutation.RemarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blog.RemarksTable,
			Columns: []string{blog.RemarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blog.RemarksTable,
			Columns: []string{blog.RemarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BlogUpdateOne is the builder for updating a single Blog entity.
type BlogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlogMutation
}

// SetTitle sets the "title" field.
func (buo *BlogUpdateOne) SetTitle(s string) *BlogUpdateOne {
	buo.mutation.SetTitle(s)
	return buo
}

// SetSubtitle sets the "subtitle" field.
func (buo *BlogUpdateOne) SetSubtitle(s string) *BlogUpdateOne {
	buo.mutation.SetSubtitle(s)
	return buo
}

// SetTime sets the "time" field.
func (buo *BlogUpdateOne) SetTime(s string) *BlogUpdateOne {
	buo.mutation.SetTime(s)
	return buo
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (buo *BlogUpdateOne) SetNillableTime(s *string) *BlogUpdateOne {
	if s != nil {
		buo.SetTime(*s)
	}
	return buo
}

// SetCover sets the "cover" field.
func (buo *BlogUpdateOne) SetCover(s string) *BlogUpdateOne {
	buo.mutation.SetCover(s)
	return buo
}

// SetHits sets the "hits" field.
func (buo *BlogUpdateOne) SetHits(i int) *BlogUpdateOne {
	buo.mutation.ResetHits()
	buo.mutation.SetHits(i)
	return buo
}

// AddHits adds i to the "hits" field.
func (buo *BlogUpdateOne) AddHits(i int) *BlogUpdateOne {
	buo.mutation.AddHits(i)
	return buo
}

// SetContentURL sets the "content_url" field.
func (buo *BlogUpdateOne) SetContentURL(s string) *BlogUpdateOne {
	buo.mutation.SetContentURL(s)
	return buo
}

// AddRemarkIDs adds the "remarks" edge to the Remark entity by IDs.
func (buo *BlogUpdateOne) AddRemarkIDs(ids ...int) *BlogUpdateOne {
	buo.mutation.AddRemarkIDs(ids...)
	return buo
}

// AddRemarks adds the "remarks" edges to the Remark entity.
func (buo *BlogUpdateOne) AddRemarks(r ...*Remark) *BlogUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return buo.AddRemarkIDs(ids...)
}

// Mutation returns the BlogMutation object of the builder.
func (buo *BlogUpdateOne) Mutation() *BlogMutation {
	return buo.mutation
}

// ClearRemarks clears all "remarks" edges to the Remark entity.
func (buo *BlogUpdateOne) ClearRemarks() *BlogUpdateOne {
	buo.mutation.ClearRemarks()
	return buo
}

// RemoveRemarkIDs removes the "remarks" edge to Remark entities by IDs.
func (buo *BlogUpdateOne) RemoveRemarkIDs(ids ...int) *BlogUpdateOne {
	buo.mutation.RemoveRemarkIDs(ids...)
	return buo
}

// RemoveRemarks removes "remarks" edges to Remark entities.
func (buo *BlogUpdateOne) RemoveRemarks(r ...*Remark) *BlogUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return buo.RemoveRemarkIDs(ids...)
}

// Where appends a list predicates to the BlogUpdate builder.
func (buo *BlogUpdateOne) Where(ps ...predicate.Blog) *BlogUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BlogUpdateOne) Select(field string, fields ...string) *BlogUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Blog entity.
func (buo *BlogUpdateOne) Save(ctx context.Context) (*Blog, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BlogUpdateOne) SaveX(ctx context.Context) *Blog {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BlogUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BlogUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BlogUpdateOne) check() error {
	if v, ok := buo.mutation.Title(); ok {
		if err := blog.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Blog.title": %w`, err)}
		}
	}
	if v, ok := buo.mutation.Subtitle(); ok {
		if err := blog.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "Blog.subtitle": %w`, err)}
		}
	}
	if v, ok := buo.mutation.Hits(); ok {
		if err := blog.HitsValidator(v); err != nil {
			return &ValidationError{Name: "hits", err: fmt.Errorf(`ent: validator failed for field "Blog.hits": %w`, err)}
		}
	}
	if v, ok := buo.mutation.ContentURL(); ok {
		if err := blog.ContentURLValidator(v); err != nil {
			return &ValidationError{Name: "content_url", err: fmt.Errorf(`ent: validator failed for field "Blog.content_url": %w`, err)}
		}
	}
	return nil
}

func (buo *BlogUpdateOne) sqlSave(ctx context.Context) (_node *Blog, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blog.Table, blog.Columns, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Blog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blog.FieldID)
		for _, f := range fields {
			if !blog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
	}
	if value, ok := buo.mutation.Subtitle(); ok {
		_spec.SetField(blog.FieldSubtitle, field.TypeString, value)
	}
	if value, ok := buo.mutation.Time(); ok {
		_spec.SetField(blog.FieldTime, field.TypeString, value)
	}
	if value, ok := buo.mutation.Cover(); ok {
		_spec.SetField(blog.FieldCover, field.TypeString, value)
	}
	if value, ok := buo.mutation.Hits(); ok {
		_spec.SetField(blog.FieldHits, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedHits(); ok {
		_spec.AddField(blog.FieldHits, field.TypeInt, value)
	}
	if value, ok := buo.mutation.ContentURL(); ok {
		_spec.SetField(blog.FieldContentURL, field.TypeString, value)
	}
	if buo.mutation.RemarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blog.RemarksTable,
			Columns: []string{blog.RemarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedRemarksIDs(); len(nodes) > 0 && !buo.mutation.RemarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blog.RemarksTable,
			Columns: []string{blog.RemarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blog.RemarksTable,
			Columns: []string{blog.RemarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Blog{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
