// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/blog"
	"server/ent/remark"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlogCreate is the builder for creating a Blog entity.
type BlogCreate struct {
	config
	mutation *BlogMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (bc *BlogCreate) SetTitle(s string) *BlogCreate {
	bc.mutation.SetTitle(s)
	return bc
}

// SetSubtitle sets the "subtitle" field.
func (bc *BlogCreate) SetSubtitle(s string) *BlogCreate {
	bc.mutation.SetSubtitle(s)
	return bc
}

// SetTime sets the "time" field.
func (bc *BlogCreate) SetTime(s string) *BlogCreate {
	bc.mutation.SetTime(s)
	return bc
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (bc *BlogCreate) SetNillableTime(s *string) *BlogCreate {
	if s != nil {
		bc.SetTime(*s)
	}
	return bc
}

// SetCover sets the "cover" field.
func (bc *BlogCreate) SetCover(s string) *BlogCreate {
	bc.mutation.SetCover(s)
	return bc
}

// SetHits sets the "hits" field.
func (bc *BlogCreate) SetHits(i int) *BlogCreate {
	bc.mutation.SetHits(i)
	return bc
}

// SetContentURL sets the "content_url" field.
func (bc *BlogCreate) SetContentURL(s string) *BlogCreate {
	bc.mutation.SetContentURL(s)
	return bc
}

// AddRemarkIDs adds the "remarks" edge to the Remark entity by IDs.
func (bc *BlogCreate) AddRemarkIDs(ids ...int) *BlogCreate {
	bc.mutation.AddRemarkIDs(ids...)
	return bc
}

// AddRemarks adds the "remarks" edges to the Remark entity.
func (bc *BlogCreate) AddRemarks(r ...*Remark) *BlogCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return bc.AddRemarkIDs(ids...)
}

// Mutation returns the BlogMutation object of the builder.
func (bc *BlogCreate) Mutation() *BlogMutation {
	return bc.mutation
}

// Save creates the Blog in the database.
func (bc *BlogCreate) Save(ctx context.Context) (*Blog, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BlogCreate) SaveX(ctx context.Context) *Blog {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BlogCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BlogCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BlogCreate) defaults() {
	if _, ok := bc.mutation.Time(); !ok {
		v := blog.DefaultTime
		bc.mutation.SetTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BlogCreate) check() error {
	if _, ok := bc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Blog.title"`)}
	}
	if v, ok := bc.mutation.Title(); ok {
		if err := blog.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Blog.title": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Subtitle(); !ok {
		return &ValidationError{Name: "subtitle", err: errors.New(`ent: missing required field "Blog.subtitle"`)}
	}
	if v, ok := bc.mutation.Subtitle(); ok {
		if err := blog.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "Blog.subtitle": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "Blog.time"`)}
	}
	if _, ok := bc.mutation.Cover(); !ok {
		return &ValidationError{Name: "cover", err: errors.New(`ent: missing required field "Blog.cover"`)}
	}
	if _, ok := bc.mutation.Hits(); !ok {
		return &ValidationError{Name: "hits", err: errors.New(`ent: missing required field "Blog.hits"`)}
	}
	if v, ok := bc.mutation.Hits(); ok {
		if err := blog.HitsValidator(v); err != nil {
			return &ValidationError{Name: "hits", err: fmt.Errorf(`ent: validator failed for field "Blog.hits": %w`, err)}
		}
	}
	if _, ok := bc.mutation.ContentURL(); !ok {
		return &ValidationError{Name: "content_url", err: errors.New(`ent: missing required field "Blog.content_url"`)}
	}
	if v, ok := bc.mutation.ContentURL(); ok {
		if err := blog.ContentURLValidator(v); err != nil {
			return &ValidationError{Name: "content_url", err: fmt.Errorf(`ent: validator failed for field "Blog.content_url": %w`, err)}
		}
	}
	return nil
}

func (bc *BlogCreate) sqlSave(ctx context.Context) (*Blog, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BlogCreate) createSpec() (*Blog, *sqlgraph.CreateSpec) {
	var (
		_node = &Blog{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(blog.Table, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt))
	)
	if value, ok := bc.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := bc.mutation.Subtitle(); ok {
		_spec.SetField(blog.FieldSubtitle, field.TypeString, value)
		_node.Subtitle = value
	}
	if value, ok := bc.mutation.Time(); ok {
		_spec.SetField(blog.FieldTime, field.TypeString, value)
		_node.Time = value
	}
	if value, ok := bc.mutation.Cover(); ok {
		_spec.SetField(blog.FieldCover, field.TypeString, value)
		_node.Cover = value
	}
	if value, ok := bc.mutation.Hits(); ok {
		_spec.SetField(blog.FieldHits, field.TypeInt, value)
		_node.Hits = value
	}
	if value, ok := bc.mutation.ContentURL(); ok {
		_spec.SetField(blog.FieldContentURL, field.TypeString, value)
		_node.ContentURL = value
	}
	if nodes := bc.mutation.RemarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blog.RemarksTable,
			Columns: []string{blog.RemarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BlogCreateBulk is the builder for creating many Blog entities in bulk.
type BlogCreateBulk struct {
	config
	builders []*BlogCreate
}

// Save creates the Blog entities in the database.
func (bcb *BlogCreateBulk) Save(ctx context.Context) ([]*Blog, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Blog, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BlogCreateBulk) SaveX(ctx context.Context) []*Blog {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BlogCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BlogCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
