// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/blog"
	"server/ent/predicate"
	"server/ent/remark"
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeBlog   = "Blog"
	TypeRemark = "Remark"
)

// BlogMutation represents an operation that mutates the Blog nodes in the graph.
type BlogMutation struct {
	config
	op             Op
	typ            string
	id             *int
	title          *string
	subtitle       *string
	time           *string
	cover          *string
	hits           *int
	addhits        *int
	content_url    *string
	clearedFields  map[string]struct{}
	remarks        map[int]struct{}
	removedremarks map[int]struct{}
	clearedremarks bool
	done           bool
	oldValue       func(context.Context) (*Blog, error)
	predicates     []predicate.Blog
}

var _ ent.Mutation = (*BlogMutation)(nil)

// blogOption allows management of the mutation configuration using functional options.
type blogOption func(*BlogMutation)

// newBlogMutation creates new mutation for the Blog entity.
func newBlogMutation(c config, op Op, opts ...blogOption) *BlogMutation {
	m := &BlogMutation{
		config:        c,
		op:            op,
		typ:           TypeBlog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withBlogID sets the ID field of the mutation.
func withBlogID(id int) blogOption {
	return func(m *BlogMutation) {
		var (
			err   error
			once  sync.Once
			value *Blog
		)
		m.oldValue = func(ctx context.Context) (*Blog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Blog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withBlog sets the old Blog of the mutation.
func withBlog(node *Blog) blogOption {
	return func(m *BlogMutation) {
		m.oldValue = func(context.Context) (*Blog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m BlogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m BlogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *BlogMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *BlogMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Blog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTitle sets the "title" field.
func (m *BlogMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *BlogMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Blog entity.
// If the Blog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlogMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *BlogMutation) ResetTitle() {
	m.title = nil
}

// SetSubtitle sets the "subtitle" field.
func (m *BlogMutation) SetSubtitle(s string) {
	m.subtitle = &s
}

// Subtitle returns the value of the "subtitle" field in the mutation.
func (m *BlogMutation) Subtitle() (r string, exists bool) {
	v := m.subtitle
	if v == nil {
		return
	}
	return *v, true
}

// OldSubtitle returns the old "subtitle" field's value of the Blog entity.
// If the Blog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlogMutation) OldSubtitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubtitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubtitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubtitle: %w", err)
	}
	return oldValue.Subtitle, nil
}

// ResetSubtitle resets all changes to the "subtitle" field.
func (m *BlogMutation) ResetSubtitle() {
	m.subtitle = nil
}

// SetTime sets the "time" field.
func (m *BlogMutation) SetTime(s string) {
	m.time = &s
}

// Time returns the value of the "time" field in the mutation.
func (m *BlogMutation) Time() (r string, exists bool) {
	v := m.time
	if v == nil {
		return
	}
	return *v, true
}

// OldTime returns the old "time" field's value of the Blog entity.
// If the Blog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlogMutation) OldTime(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTime: %w", err)
	}
	return oldValue.Time, nil
}

// ResetTime resets all changes to the "time" field.
func (m *BlogMutation) ResetTime() {
	m.time = nil
}

// SetCover sets the "cover" field.
func (m *BlogMutation) SetCover(s string) {
	m.cover = &s
}

// Cover returns the value of the "cover" field in the mutation.
func (m *BlogMutation) Cover() (r string, exists bool) {
	v := m.cover
	if v == nil {
		return
	}
	return *v, true
}

// OldCover returns the old "cover" field's value of the Blog entity.
// If the Blog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlogMutation) OldCover(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCover is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCover requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCover: %w", err)
	}
	return oldValue.Cover, nil
}

// ResetCover resets all changes to the "cover" field.
func (m *BlogMutation) ResetCover() {
	m.cover = nil
}

// SetHits sets the "hits" field.
func (m *BlogMutation) SetHits(i int) {
	m.hits = &i
	m.addhits = nil
}

// Hits returns the value of the "hits" field in the mutation.
func (m *BlogMutation) Hits() (r int, exists bool) {
	v := m.hits
	if v == nil {
		return
	}
	return *v, true
}

// OldHits returns the old "hits" field's value of the Blog entity.
// If the Blog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlogMutation) OldHits(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHits is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHits requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHits: %w", err)
	}
	return oldValue.Hits, nil
}

// AddHits adds i to the "hits" field.
func (m *BlogMutation) AddHits(i int) {
	if m.addhits != nil {
		*m.addhits += i
	} else {
		m.addhits = &i
	}
}

// AddedHits returns the value that was added to the "hits" field in this mutation.
func (m *BlogMutation) AddedHits() (r int, exists bool) {
	v := m.addhits
	if v == nil {
		return
	}
	return *v, true
}

// ResetHits resets all changes to the "hits" field.
func (m *BlogMutation) ResetHits() {
	m.hits = nil
	m.addhits = nil
}

// SetContentURL sets the "content_url" field.
func (m *BlogMutation) SetContentURL(s string) {
	m.content_url = &s
}

// ContentURL returns the value of the "content_url" field in the mutation.
func (m *BlogMutation) ContentURL() (r string, exists bool) {
	v := m.content_url
	if v == nil {
		return
	}
	return *v, true
}

// OldContentURL returns the old "content_url" field's value of the Blog entity.
// If the Blog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlogMutation) OldContentURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContentURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContentURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContentURL: %w", err)
	}
	return oldValue.ContentURL, nil
}

// ResetContentURL resets all changes to the "content_url" field.
func (m *BlogMutation) ResetContentURL() {
	m.content_url = nil
}

// AddRemarkIDs adds the "remarks" edge to the Remark entity by ids.
func (m *BlogMutation) AddRemarkIDs(ids ...int) {
	if m.remarks == nil {
		m.remarks = make(map[int]struct{})
	}
	for i := range ids {
		m.remarks[ids[i]] = struct{}{}
	}
}

// ClearRemarks clears the "remarks" edge to the Remark entity.
func (m *BlogMutation) ClearRemarks() {
	m.clearedremarks = true
}

// RemarksCleared reports if the "remarks" edge to the Remark entity was cleared.
func (m *BlogMutation) RemarksCleared() bool {
	return m.clearedremarks
}

// RemoveRemarkIDs removes the "remarks" edge to the Remark entity by IDs.
func (m *BlogMutation) RemoveRemarkIDs(ids ...int) {
	if m.removedremarks == nil {
		m.removedremarks = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.remarks, ids[i])
		m.removedremarks[ids[i]] = struct{}{}
	}
}

// RemovedRemarks returns the removed IDs of the "remarks" edge to the Remark entity.
func (m *BlogMutation) RemovedRemarksIDs() (ids []int) {
	for id := range m.removedremarks {
		ids = append(ids, id)
	}
	return
}

// RemarksIDs returns the "remarks" edge IDs in the mutation.
func (m *BlogMutation) RemarksIDs() (ids []int) {
	for id := range m.remarks {
		ids = append(ids, id)
	}
	return
}

// ResetRemarks resets all changes to the "remarks" edge.
func (m *BlogMutation) ResetRemarks() {
	m.remarks = nil
	m.clearedremarks = false
	m.removedremarks = nil
}

// Where appends a list predicates to the BlogMutation builder.
func (m *BlogMutation) Where(ps ...predicate.Blog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the BlogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *BlogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Blog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *BlogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *BlogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Blog).
func (m *BlogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *BlogMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.title != nil {
		fields = append(fields, blog.FieldTitle)
	}
	if m.subtitle != nil {
		fields = append(fields, blog.FieldSubtitle)
	}
	if m.time != nil {
		fields = append(fields, blog.FieldTime)
	}
	if m.cover != nil {
		fields = append(fields, blog.FieldCover)
	}
	if m.hits != nil {
		fields = append(fields, blog.FieldHits)
	}
	if m.content_url != nil {
		fields = append(fields, blog.FieldContentURL)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *BlogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case blog.FieldTitle:
		return m.Title()
	case blog.FieldSubtitle:
		return m.Subtitle()
	case blog.FieldTime:
		return m.Time()
	case blog.FieldCover:
		return m.Cover()
	case blog.FieldHits:
		return m.Hits()
	case blog.FieldContentURL:
		return m.ContentURL()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *BlogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case blog.FieldTitle:
		return m.OldTitle(ctx)
	case blog.FieldSubtitle:
		return m.OldSubtitle(ctx)
	case blog.FieldTime:
		return m.OldTime(ctx)
	case blog.FieldCover:
		return m.OldCover(ctx)
	case blog.FieldHits:
		return m.OldHits(ctx)
	case blog.FieldContentURL:
		return m.OldContentURL(ctx)
	}
	return nil, fmt.Errorf("unknown Blog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BlogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case blog.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case blog.FieldSubtitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubtitle(v)
		return nil
	case blog.FieldTime:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTime(v)
		return nil
	case blog.FieldCover:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCover(v)
		return nil
	case blog.FieldHits:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHits(v)
		return nil
	case blog.FieldContentURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContentURL(v)
		return nil
	}
	return fmt.Errorf("unknown Blog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *BlogMutation) AddedFields() []string {
	var fields []string
	if m.addhits != nil {
		fields = append(fields, blog.FieldHits)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *BlogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case blog.FieldHits:
		return m.AddedHits()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BlogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case blog.FieldHits:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddHits(v)
		return nil
	}
	return fmt.Errorf("unknown Blog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *BlogMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *BlogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *BlogMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Blog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *BlogMutation) ResetField(name string) error {
	switch name {
	case blog.FieldTitle:
		m.ResetTitle()
		return nil
	case blog.FieldSubtitle:
		m.ResetSubtitle()
		return nil
	case blog.FieldTime:
		m.ResetTime()
		return nil
	case blog.FieldCover:
		m.ResetCover()
		return nil
	case blog.FieldHits:
		m.ResetHits()
		return nil
	case blog.FieldContentURL:
		m.ResetContentURL()
		return nil
	}
	return fmt.Errorf("unknown Blog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *BlogMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.remarks != nil {
		edges = append(edges, blog.EdgeRemarks)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *BlogMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case blog.EdgeRemarks:
		ids := make([]ent.Value, 0, len(m.remarks))
		for id := range m.remarks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *BlogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedremarks != nil {
		edges = append(edges, blog.EdgeRemarks)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *BlogMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case blog.EdgeRemarks:
		ids := make([]ent.Value, 0, len(m.removedremarks))
		for id := range m.removedremarks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *BlogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedremarks {
		edges = append(edges, blog.EdgeRemarks)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *BlogMutation) EdgeCleared(name string) bool {
	switch name {
	case blog.EdgeRemarks:
		return m.clearedremarks
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *BlogMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Blog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *BlogMutation) ResetEdge(name string) error {
	switch name {
	case blog.EdgeRemarks:
		m.ResetRemarks()
		return nil
	}
	return fmt.Errorf("unknown Blog edge %s", name)
}

// RemarkMutation represents an operation that mutates the Remark nodes in the graph.
type RemarkMutation struct {
	config
	op            Op
	typ           string
	id            *int
	blog_id       *int
	addblog_id    *int
	is_reply      *bool
	target_id     *string
	content       *string
	create_at     *string
	if_del        *bool
	user_name     *string
	target_name   *string
	clearedFields map[string]struct{}
	blogs         *int
	clearedblogs  bool
	done          bool
	oldValue      func(context.Context) (*Remark, error)
	predicates    []predicate.Remark
}

var _ ent.Mutation = (*RemarkMutation)(nil)

// remarkOption allows management of the mutation configuration using functional options.
type remarkOption func(*RemarkMutation)

// newRemarkMutation creates new mutation for the Remark entity.
func newRemarkMutation(c config, op Op, opts ...remarkOption) *RemarkMutation {
	m := &RemarkMutation{
		config:        c,
		op:            op,
		typ:           TypeRemark,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRemarkID sets the ID field of the mutation.
func withRemarkID(id int) remarkOption {
	return func(m *RemarkMutation) {
		var (
			err   error
			once  sync.Once
			value *Remark
		)
		m.oldValue = func(ctx context.Context) (*Remark, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Remark.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRemark sets the old Remark of the mutation.
func withRemark(node *Remark) remarkOption {
	return func(m *RemarkMutation) {
		m.oldValue = func(context.Context) (*Remark, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RemarkMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RemarkMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RemarkMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RemarkMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Remark.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetBlogID sets the "blog_id" field.
func (m *RemarkMutation) SetBlogID(i int) {
	m.blog_id = &i
	m.addblog_id = nil
}

// BlogID returns the value of the "blog_id" field in the mutation.
func (m *RemarkMutation) BlogID() (r int, exists bool) {
	v := m.blog_id
	if v == nil {
		return
	}
	return *v, true
}

// OldBlogID returns the old "blog_id" field's value of the Remark entity.
// If the Remark object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RemarkMutation) OldBlogID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBlogID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBlogID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBlogID: %w", err)
	}
	return oldValue.BlogID, nil
}

// AddBlogID adds i to the "blog_id" field.
func (m *RemarkMutation) AddBlogID(i int) {
	if m.addblog_id != nil {
		*m.addblog_id += i
	} else {
		m.addblog_id = &i
	}
}

// AddedBlogID returns the value that was added to the "blog_id" field in this mutation.
func (m *RemarkMutation) AddedBlogID() (r int, exists bool) {
	v := m.addblog_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetBlogID resets all changes to the "blog_id" field.
func (m *RemarkMutation) ResetBlogID() {
	m.blog_id = nil
	m.addblog_id = nil
}

// SetIsReply sets the "is_reply" field.
func (m *RemarkMutation) SetIsReply(b bool) {
	m.is_reply = &b
}

// IsReply returns the value of the "is_reply" field in the mutation.
func (m *RemarkMutation) IsReply() (r bool, exists bool) {
	v := m.is_reply
	if v == nil {
		return
	}
	return *v, true
}

// OldIsReply returns the old "is_reply" field's value of the Remark entity.
// If the Remark object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RemarkMutation) OldIsReply(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsReply is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsReply requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsReply: %w", err)
	}
	return oldValue.IsReply, nil
}

// ResetIsReply resets all changes to the "is_reply" field.
func (m *RemarkMutation) ResetIsReply() {
	m.is_reply = nil
}

// SetTargetID sets the "target_id" field.
func (m *RemarkMutation) SetTargetID(s string) {
	m.target_id = &s
}

// TargetID returns the value of the "target_id" field in the mutation.
func (m *RemarkMutation) TargetID() (r string, exists bool) {
	v := m.target_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTargetID returns the old "target_id" field's value of the Remark entity.
// If the Remark object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RemarkMutation) OldTargetID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTargetID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTargetID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTargetID: %w", err)
	}
	return oldValue.TargetID, nil
}

// ResetTargetID resets all changes to the "target_id" field.
func (m *RemarkMutation) ResetTargetID() {
	m.target_id = nil
}

// SetContent sets the "content" field.
func (m *RemarkMutation) SetContent(s string) {
	m.content = &s
}

// Content returns the value of the "content" field in the mutation.
func (m *RemarkMutation) Content() (r string, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the Remark entity.
// If the Remark object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RemarkMutation) OldContent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// ResetContent resets all changes to the "content" field.
func (m *RemarkMutation) ResetContent() {
	m.content = nil
}

// SetCreateAt sets the "create_at" field.
func (m *RemarkMutation) SetCreateAt(s string) {
	m.create_at = &s
}

// CreateAt returns the value of the "create_at" field in the mutation.
func (m *RemarkMutation) CreateAt() (r string, exists bool) {
	v := m.create_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateAt returns the old "create_at" field's value of the Remark entity.
// If the Remark object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RemarkMutation) OldCreateAt(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateAt: %w", err)
	}
	return oldValue.CreateAt, nil
}

// ResetCreateAt resets all changes to the "create_at" field.
func (m *RemarkMutation) ResetCreateAt() {
	m.create_at = nil
}

// SetIfDel sets the "if_del" field.
func (m *RemarkMutation) SetIfDel(b bool) {
	m.if_del = &b
}

// IfDel returns the value of the "if_del" field in the mutation.
func (m *RemarkMutation) IfDel() (r bool, exists bool) {
	v := m.if_del
	if v == nil {
		return
	}
	return *v, true
}

// OldIfDel returns the old "if_del" field's value of the Remark entity.
// If the Remark object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RemarkMutation) OldIfDel(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIfDel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIfDel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIfDel: %w", err)
	}
	return oldValue.IfDel, nil
}

// ResetIfDel resets all changes to the "if_del" field.
func (m *RemarkMutation) ResetIfDel() {
	m.if_del = nil
}

// SetUserName sets the "user_name" field.
func (m *RemarkMutation) SetUserName(s string) {
	m.user_name = &s
}

// UserName returns the value of the "user_name" field in the mutation.
func (m *RemarkMutation) UserName() (r string, exists bool) {
	v := m.user_name
	if v == nil {
		return
	}
	return *v, true
}

// OldUserName returns the old "user_name" field's value of the Remark entity.
// If the Remark object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RemarkMutation) OldUserName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserName: %w", err)
	}
	return oldValue.UserName, nil
}

// ResetUserName resets all changes to the "user_name" field.
func (m *RemarkMutation) ResetUserName() {
	m.user_name = nil
}

// SetTargetName sets the "target_name" field.
func (m *RemarkMutation) SetTargetName(s string) {
	m.target_name = &s
}

// TargetName returns the value of the "target_name" field in the mutation.
func (m *RemarkMutation) TargetName() (r string, exists bool) {
	v := m.target_name
	if v == nil {
		return
	}
	return *v, true
}

// OldTargetName returns the old "target_name" field's value of the Remark entity.
// If the Remark object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RemarkMutation) OldTargetName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTargetName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTargetName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTargetName: %w", err)
	}
	return oldValue.TargetName, nil
}

// ResetTargetName resets all changes to the "target_name" field.
func (m *RemarkMutation) ResetTargetName() {
	m.target_name = nil
}

// SetBlogsID sets the "blogs" edge to the Blog entity by id.
func (m *RemarkMutation) SetBlogsID(id int) {
	m.blogs = &id
}

// ClearBlogs clears the "blogs" edge to the Blog entity.
func (m *RemarkMutation) ClearBlogs() {
	m.clearedblogs = true
}

// BlogsCleared reports if the "blogs" edge to the Blog entity was cleared.
func (m *RemarkMutation) BlogsCleared() bool {
	return m.clearedblogs
}

// BlogsID returns the "blogs" edge ID in the mutation.
func (m *RemarkMutation) BlogsID() (id int, exists bool) {
	if m.blogs != nil {
		return *m.blogs, true
	}
	return
}

// BlogsIDs returns the "blogs" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// BlogsID instead. It exists only for internal usage by the builders.
func (m *RemarkMutation) BlogsIDs() (ids []int) {
	if id := m.blogs; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetBlogs resets all changes to the "blogs" edge.
func (m *RemarkMutation) ResetBlogs() {
	m.blogs = nil
	m.clearedblogs = false
}

// Where appends a list predicates to the RemarkMutation builder.
func (m *RemarkMutation) Where(ps ...predicate.Remark) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RemarkMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RemarkMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Remark, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RemarkMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RemarkMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Remark).
func (m *RemarkMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RemarkMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.blog_id != nil {
		fields = append(fields, remark.FieldBlogID)
	}
	if m.is_reply != nil {
		fields = append(fields, remark.FieldIsReply)
	}
	if m.target_id != nil {
		fields = append(fields, remark.FieldTargetID)
	}
	if m.content != nil {
		fields = append(fields, remark.FieldContent)
	}
	if m.create_at != nil {
		fields = append(fields, remark.FieldCreateAt)
	}
	if m.if_del != nil {
		fields = append(fields, remark.FieldIfDel)
	}
	if m.user_name != nil {
		fields = append(fields, remark.FieldUserName)
	}
	if m.target_name != nil {
		fields = append(fields, remark.FieldTargetName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RemarkMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case remark.FieldBlogID:
		return m.BlogID()
	case remark.FieldIsReply:
		return m.IsReply()
	case remark.FieldTargetID:
		return m.TargetID()
	case remark.FieldContent:
		return m.Content()
	case remark.FieldCreateAt:
		return m.CreateAt()
	case remark.FieldIfDel:
		return m.IfDel()
	case remark.FieldUserName:
		return m.UserName()
	case remark.FieldTargetName:
		return m.TargetName()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RemarkMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case remark.FieldBlogID:
		return m.OldBlogID(ctx)
	case remark.FieldIsReply:
		return m.OldIsReply(ctx)
	case remark.FieldTargetID:
		return m.OldTargetID(ctx)
	case remark.FieldContent:
		return m.OldContent(ctx)
	case remark.FieldCreateAt:
		return m.OldCreateAt(ctx)
	case remark.FieldIfDel:
		return m.OldIfDel(ctx)
	case remark.FieldUserName:
		return m.OldUserName(ctx)
	case remark.FieldTargetName:
		return m.OldTargetName(ctx)
	}
	return nil, fmt.Errorf("unknown Remark field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RemarkMutation) SetField(name string, value ent.Value) error {
	switch name {
	case remark.FieldBlogID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBlogID(v)
		return nil
	case remark.FieldIsReply:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsReply(v)
		return nil
	case remark.FieldTargetID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTargetID(v)
		return nil
	case remark.FieldContent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case remark.FieldCreateAt:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateAt(v)
		return nil
	case remark.FieldIfDel:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIfDel(v)
		return nil
	case remark.FieldUserName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserName(v)
		return nil
	case remark.FieldTargetName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTargetName(v)
		return nil
	}
	return fmt.Errorf("unknown Remark field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RemarkMutation) AddedFields() []string {
	var fields []string
	if m.addblog_id != nil {
		fields = append(fields, remark.FieldBlogID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RemarkMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case remark.FieldBlogID:
		return m.AddedBlogID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RemarkMutation) AddField(name string, value ent.Value) error {
	switch name {
	case remark.FieldBlogID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBlogID(v)
		return nil
	}
	return fmt.Errorf("unknown Remark numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RemarkMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RemarkMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RemarkMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Remark nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RemarkMutation) ResetField(name string) error {
	switch name {
	case remark.FieldBlogID:
		m.ResetBlogID()
		return nil
	case remark.FieldIsReply:
		m.ResetIsReply()
		return nil
	case remark.FieldTargetID:
		m.ResetTargetID()
		return nil
	case remark.FieldContent:
		m.ResetContent()
		return nil
	case remark.FieldCreateAt:
		m.ResetCreateAt()
		return nil
	case remark.FieldIfDel:
		m.ResetIfDel()
		return nil
	case remark.FieldUserName:
		m.ResetUserName()
		return nil
	case remark.FieldTargetName:
		m.ResetTargetName()
		return nil
	}
	return fmt.Errorf("unknown Remark field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RemarkMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.blogs != nil {
		edges = append(edges, remark.EdgeBlogs)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RemarkMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case remark.EdgeBlogs:
		if id := m.blogs; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RemarkMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RemarkMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RemarkMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedblogs {
		edges = append(edges, remark.EdgeBlogs)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RemarkMutation) EdgeCleared(name string) bool {
	switch name {
	case remark.EdgeBlogs:
		return m.clearedblogs
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RemarkMutation) ClearEdge(name string) error {
	switch name {
	case remark.EdgeBlogs:
		m.ClearBlogs()
		return nil
	}
	return fmt.Errorf("unknown Remark unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RemarkMutation) ResetEdge(name string) error {
	switch name {
	case remark.EdgeBlogs:
		m.ResetBlogs()
		return nil
	}
	return fmt.Errorf("unknown Remark edge %s", name)
}
