// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/blog"
	"server/ent/remark"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RemarkCreate is the builder for creating a Remark entity.
type RemarkCreate struct {
	config
	mutation *RemarkMutation
	hooks    []Hook
}

// SetBlogID sets the "blog_id" field.
func (rc *RemarkCreate) SetBlogID(i int) *RemarkCreate {
	rc.mutation.SetBlogID(i)
	return rc
}

// SetIsReply sets the "is_reply" field.
func (rc *RemarkCreate) SetIsReply(b bool) *RemarkCreate {
	rc.mutation.SetIsReply(b)
	return rc
}

// SetNillableIsReply sets the "is_reply" field if the given value is not nil.
func (rc *RemarkCreate) SetNillableIsReply(b *bool) *RemarkCreate {
	if b != nil {
		rc.SetIsReply(*b)
	}
	return rc
}

// SetTargetID sets the "target_id" field.
func (rc *RemarkCreate) SetTargetID(s string) *RemarkCreate {
	rc.mutation.SetTargetID(s)
	return rc
}

// SetContent sets the "content" field.
func (rc *RemarkCreate) SetContent(s string) *RemarkCreate {
	rc.mutation.SetContent(s)
	return rc
}

// SetCreateAt sets the "create_at" field.
func (rc *RemarkCreate) SetCreateAt(s string) *RemarkCreate {
	rc.mutation.SetCreateAt(s)
	return rc
}

// SetIfDel sets the "if_del" field.
func (rc *RemarkCreate) SetIfDel(b bool) *RemarkCreate {
	rc.mutation.SetIfDel(b)
	return rc
}

// SetNillableIfDel sets the "if_del" field if the given value is not nil.
func (rc *RemarkCreate) SetNillableIfDel(b *bool) *RemarkCreate {
	if b != nil {
		rc.SetIfDel(*b)
	}
	return rc
}

// SetUserName sets the "user_name" field.
func (rc *RemarkCreate) SetUserName(s string) *RemarkCreate {
	rc.mutation.SetUserName(s)
	return rc
}

// SetTargetName sets the "target_name" field.
func (rc *RemarkCreate) SetTargetName(s string) *RemarkCreate {
	rc.mutation.SetTargetName(s)
	return rc
}

// SetBlogsID sets the "blogs" edge to the Blog entity by ID.
func (rc *RemarkCreate) SetBlogsID(id int) *RemarkCreate {
	rc.mutation.SetBlogsID(id)
	return rc
}

// SetNillableBlogsID sets the "blogs" edge to the Blog entity by ID if the given value is not nil.
func (rc *RemarkCreate) SetNillableBlogsID(id *int) *RemarkCreate {
	if id != nil {
		rc = rc.SetBlogsID(*id)
	}
	return rc
}

// SetBlogs sets the "blogs" edge to the Blog entity.
func (rc *RemarkCreate) SetBlogs(b *Blog) *RemarkCreate {
	return rc.SetBlogsID(b.ID)
}

// Mutation returns the RemarkMutation object of the builder.
func (rc *RemarkCreate) Mutation() *RemarkMutation {
	return rc.mutation
}

// Save creates the Remark in the database.
func (rc *RemarkCreate) Save(ctx context.Context) (*Remark, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RemarkCreate) SaveX(ctx context.Context) *Remark {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RemarkCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RemarkCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RemarkCreate) defaults() {
	if _, ok := rc.mutation.IsReply(); !ok {
		v := remark.DefaultIsReply
		rc.mutation.SetIsReply(v)
	}
	if _, ok := rc.mutation.IfDel(); !ok {
		v := remark.DefaultIfDel
		rc.mutation.SetIfDel(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RemarkCreate) check() error {
	if _, ok := rc.mutation.BlogID(); !ok {
		return &ValidationError{Name: "blog_id", err: errors.New(`ent: missing required field "Remark.blog_id"`)}
	}
	if _, ok := rc.mutation.IsReply(); !ok {
		return &ValidationError{Name: "is_reply", err: errors.New(`ent: missing required field "Remark.is_reply"`)}
	}
	if _, ok := rc.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "Remark.target_id"`)}
	}
	if _, ok := rc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Remark.content"`)}
	}
	if v, ok := rc.mutation.Content(); ok {
		if err := remark.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Remark.content": %w`, err)}
		}
	}
	if _, ok := rc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "Remark.create_at"`)}
	}
	if v, ok := rc.mutation.CreateAt(); ok {
		if err := remark.CreateAtValidator(v); err != nil {
			return &ValidationError{Name: "create_at", err: fmt.Errorf(`ent: validator failed for field "Remark.create_at": %w`, err)}
		}
	}
	if _, ok := rc.mutation.IfDel(); !ok {
		return &ValidationError{Name: "if_del", err: errors.New(`ent: missing required field "Remark.if_del"`)}
	}
	if _, ok := rc.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New(`ent: missing required field "Remark.user_name"`)}
	}
	if v, ok := rc.mutation.UserName(); ok {
		if err := remark.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "Remark.user_name": %w`, err)}
		}
	}
	if _, ok := rc.mutation.TargetName(); !ok {
		return &ValidationError{Name: "target_name", err: errors.New(`ent: missing required field "Remark.target_name"`)}
	}
	if v, ok := rc.mutation.TargetName(); ok {
		if err := remark.TargetNameValidator(v); err != nil {
			return &ValidationError{Name: "target_name", err: fmt.Errorf(`ent: validator failed for field "Remark.target_name": %w`, err)}
		}
	}
	return nil
}

func (rc *RemarkCreate) sqlSave(ctx context.Context) (*Remark, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RemarkCreate) createSpec() (*Remark, *sqlgraph.CreateSpec) {
	var (
		_node = &Remark{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(remark.Table, sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.BlogID(); ok {
		_spec.SetField(remark.FieldBlogID, field.TypeInt, value)
		_node.BlogID = value
	}
	if value, ok := rc.mutation.IsReply(); ok {
		_spec.SetField(remark.FieldIsReply, field.TypeBool, value)
		_node.IsReply = value
	}
	if value, ok := rc.mutation.TargetID(); ok {
		_spec.SetField(remark.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := rc.mutation.Content(); ok {
		_spec.SetField(remark.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := rc.mutation.CreateAt(); ok {
		_spec.SetField(remark.FieldCreateAt, field.TypeString, value)
		_node.CreateAt = value
	}
	if value, ok := rc.mutation.IfDel(); ok {
		_spec.SetField(remark.FieldIfDel, field.TypeBool, value)
		_node.IfDel = value
	}
	if value, ok := rc.mutation.UserName(); ok {
		_spec.SetField(remark.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := rc.mutation.TargetName(); ok {
		_spec.SetField(remark.FieldTargetName, field.TypeString, value)
		_node.TargetName = value
	}
	if nodes := rc.mutation.BlogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   remark.BlogsTable,
			Columns: []string{remark.BlogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.blog_remarks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RemarkCreateBulk is the builder for creating many Remark entities in bulk.
type RemarkCreateBulk struct {
	config
	builders []*RemarkCreate
}

// Save creates the Remark entities in the database.
func (rcb *RemarkCreateBulk) Save(ctx context.Context) ([]*Remark, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Remark, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RemarkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RemarkCreateBulk) SaveX(ctx context.Context) []*Remark {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RemarkCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RemarkCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
