// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/blog"
	"server/ent/predicate"
	"server/ent/remark"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RemarkUpdate is the builder for updating Remark entities.
type RemarkUpdate struct {
	config
	hooks    []Hook
	mutation *RemarkMutation
}

// Where appends a list predicates to the RemarkUpdate builder.
func (ru *RemarkUpdate) Where(ps ...predicate.Remark) *RemarkUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetBlogID sets the "blog_id" field.
func (ru *RemarkUpdate) SetBlogID(i int) *RemarkUpdate {
	ru.mutation.ResetBlogID()
	ru.mutation.SetBlogID(i)
	return ru
}

// AddBlogID adds i to the "blog_id" field.
func (ru *RemarkUpdate) AddBlogID(i int) *RemarkUpdate {
	ru.mutation.AddBlogID(i)
	return ru
}

// SetIsReply sets the "is_reply" field.
func (ru *RemarkUpdate) SetIsReply(b bool) *RemarkUpdate {
	ru.mutation.SetIsReply(b)
	return ru
}

// SetNillableIsReply sets the "is_reply" field if the given value is not nil.
func (ru *RemarkUpdate) SetNillableIsReply(b *bool) *RemarkUpdate {
	if b != nil {
		ru.SetIsReply(*b)
	}
	return ru
}

// SetTargetID sets the "target_id" field.
func (ru *RemarkUpdate) SetTargetID(s string) *RemarkUpdate {
	ru.mutation.SetTargetID(s)
	return ru
}

// SetContent sets the "content" field.
func (ru *RemarkUpdate) SetContent(s string) *RemarkUpdate {
	ru.mutation.SetContent(s)
	return ru
}

// SetCreateAt sets the "create_at" field.
func (ru *RemarkUpdate) SetCreateAt(s string) *RemarkUpdate {
	ru.mutation.SetCreateAt(s)
	return ru
}

// SetIfDel sets the "if_del" field.
func (ru *RemarkUpdate) SetIfDel(b bool) *RemarkUpdate {
	ru.mutation.SetIfDel(b)
	return ru
}

// SetNillableIfDel sets the "if_del" field if the given value is not nil.
func (ru *RemarkUpdate) SetNillableIfDel(b *bool) *RemarkUpdate {
	if b != nil {
		ru.SetIfDel(*b)
	}
	return ru
}

// SetUserName sets the "user_name" field.
func (ru *RemarkUpdate) SetUserName(s string) *RemarkUpdate {
	ru.mutation.SetUserName(s)
	return ru
}

// SetTargetName sets the "target_name" field.
func (ru *RemarkUpdate) SetTargetName(s string) *RemarkUpdate {
	ru.mutation.SetTargetName(s)
	return ru
}

// SetBlogsID sets the "blogs" edge to the Blog entity by ID.
func (ru *RemarkUpdate) SetBlogsID(id int) *RemarkUpdate {
	ru.mutation.SetBlogsID(id)
	return ru
}

// SetNillableBlogsID sets the "blogs" edge to the Blog entity by ID if the given value is not nil.
func (ru *RemarkUpdate) SetNillableBlogsID(id *int) *RemarkUpdate {
	if id != nil {
		ru = ru.SetBlogsID(*id)
	}
	return ru
}

// SetBlogs sets the "blogs" edge to the Blog entity.
func (ru *RemarkUpdate) SetBlogs(b *Blog) *RemarkUpdate {
	return ru.SetBlogsID(b.ID)
}

// Mutation returns the RemarkMutation object of the builder.
func (ru *RemarkUpdate) Mutation() *RemarkMutation {
	return ru.mutation
}

// ClearBlogs clears the "blogs" edge to the Blog entity.
func (ru *RemarkUpdate) ClearBlogs() *RemarkUpdate {
	ru.mutation.ClearBlogs()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RemarkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RemarkUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RemarkUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RemarkUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RemarkUpdate) check() error {
	if v, ok := ru.mutation.Content(); ok {
		if err := remark.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Remark.content": %w`, err)}
		}
	}
	if v, ok := ru.mutation.CreateAt(); ok {
		if err := remark.CreateAtValidator(v); err != nil {
			return &ValidationError{Name: "create_at", err: fmt.Errorf(`ent: validator failed for field "Remark.create_at": %w`, err)}
		}
	}
	if v, ok := ru.mutation.UserName(); ok {
		if err := remark.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "Remark.user_name": %w`, err)}
		}
	}
	if v, ok := ru.mutation.TargetName(); ok {
		if err := remark.TargetNameValidator(v); err != nil {
			return &ValidationError{Name: "target_name", err: fmt.Errorf(`ent: validator failed for field "Remark.target_name": %w`, err)}
		}
	}
	return nil
}

func (ru *RemarkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(remark.Table, remark.Columns, sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.BlogID(); ok {
		_spec.SetField(remark.FieldBlogID, field.TypeInt, value)
	}
	if value, ok := ru.mutation.AddedBlogID(); ok {
		_spec.AddField(remark.FieldBlogID, field.TypeInt, value)
	}
	if value, ok := ru.mutation.IsReply(); ok {
		_spec.SetField(remark.FieldIsReply, field.TypeBool, value)
	}
	if value, ok := ru.mutation.TargetID(); ok {
		_spec.SetField(remark.FieldTargetID, field.TypeString, value)
	}
	if value, ok := ru.mutation.Content(); ok {
		_spec.SetField(remark.FieldContent, field.TypeString, value)
	}
	if value, ok := ru.mutation.CreateAt(); ok {
		_spec.SetField(remark.FieldCreateAt, field.TypeString, value)
	}
	if value, ok := ru.mutation.IfDel(); ok {
		_spec.SetField(remark.FieldIfDel, field.TypeBool, value)
	}
	if value, ok := ru.mutation.UserName(); ok {
		_spec.SetField(remark.FieldUserName, field.TypeString, value)
	}
	if value, ok := ru.mutation.TargetName(); ok {
		_spec.SetField(remark.FieldTargetName, field.TypeString, value)
	}
	if ru.mutation.BlogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   remark.BlogsTable,
			Columns: []string{remark.BlogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.BlogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   remark.BlogsTable,
			Columns: []string{remark.BlogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RemarkUpdateOne is the builder for updating a single Remark entity.
type RemarkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RemarkMutation
}

// SetBlogID sets the "blog_id" field.
func (ruo *RemarkUpdateOne) SetBlogID(i int) *RemarkUpdateOne {
	ruo.mutation.ResetBlogID()
	ruo.mutation.SetBlogID(i)
	return ruo
}

// AddBlogID adds i to the "blog_id" field.
func (ruo *RemarkUpdateOne) AddBlogID(i int) *RemarkUpdateOne {
	ruo.mutation.AddBlogID(i)
	return ruo
}

// SetIsReply sets the "is_reply" field.
func (ruo *RemarkUpdateOne) SetIsReply(b bool) *RemarkUpdateOne {
	ruo.mutation.SetIsReply(b)
	return ruo
}

// SetNillableIsReply sets the "is_reply" field if the given value is not nil.
func (ruo *RemarkUpdateOne) SetNillableIsReply(b *bool) *RemarkUpdateOne {
	if b != nil {
		ruo.SetIsReply(*b)
	}
	return ruo
}

// SetTargetID sets the "target_id" field.
func (ruo *RemarkUpdateOne) SetTargetID(s string) *RemarkUpdateOne {
	ruo.mutation.SetTargetID(s)
	return ruo
}

// SetContent sets the "content" field.
func (ruo *RemarkUpdateOne) SetContent(s string) *RemarkUpdateOne {
	ruo.mutation.SetContent(s)
	return ruo
}

// SetCreateAt sets the "create_at" field.
func (ruo *RemarkUpdateOne) SetCreateAt(s string) *RemarkUpdateOne {
	ruo.mutation.SetCreateAt(s)
	return ruo
}

// SetIfDel sets the "if_del" field.
func (ruo *RemarkUpdateOne) SetIfDel(b bool) *RemarkUpdateOne {
	ruo.mutation.SetIfDel(b)
	return ruo
}

// SetNillableIfDel sets the "if_del" field if the given value is not nil.
func (ruo *RemarkUpdateOne) SetNillableIfDel(b *bool) *RemarkUpdateOne {
	if b != nil {
		ruo.SetIfDel(*b)
	}
	return ruo
}

// SetUserName sets the "user_name" field.
func (ruo *RemarkUpdateOne) SetUserName(s string) *RemarkUpdateOne {
	ruo.mutation.SetUserName(s)
	return ruo
}

// SetTargetName sets the "target_name" field.
func (ruo *RemarkUpdateOne) SetTargetName(s string) *RemarkUpdateOne {
	ruo.mutation.SetTargetName(s)
	return ruo
}

// SetBlogsID sets the "blogs" edge to the Blog entity by ID.
func (ruo *RemarkUpdateOne) SetBlogsID(id int) *RemarkUpdateOne {
	ruo.mutation.SetBlogsID(id)
	return ruo
}

// SetNillableBlogsID sets the "blogs" edge to the Blog entity by ID if the given value is not nil.
func (ruo *RemarkUpdateOne) SetNillableBlogsID(id *int) *RemarkUpdateOne {
	if id != nil {
		ruo = ruo.SetBlogsID(*id)
	}
	return ruo
}

// SetBlogs sets the "blogs" edge to the Blog entity.
func (ruo *RemarkUpdateOne) SetBlogs(b *Blog) *RemarkUpdateOne {
	return ruo.SetBlogsID(b.ID)
}

// Mutation returns the RemarkMutation object of the builder.
func (ruo *RemarkUpdateOne) Mutation() *RemarkMutation {
	return ruo.mutation
}

// ClearBlogs clears the "blogs" edge to the Blog entity.
func (ruo *RemarkUpdateOne) ClearBlogs() *RemarkUpdateOne {
	ruo.mutation.ClearBlogs()
	return ruo
}

// Where appends a list predicates to the RemarkUpdate builder.
func (ruo *RemarkUpdateOne) Where(ps ...predicate.Remark) *RemarkUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RemarkUpdateOne) Select(field string, fields ...string) *RemarkUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Remark entity.
func (ruo *RemarkUpdateOne) Save(ctx context.Context) (*Remark, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RemarkUpdateOne) SaveX(ctx context.Context) *Remark {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RemarkUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RemarkUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RemarkUpdateOne) check() error {
	if v, ok := ruo.mutation.Content(); ok {
		if err := remark.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Remark.content": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.CreateAt(); ok {
		if err := remark.CreateAtValidator(v); err != nil {
			return &ValidationError{Name: "create_at", err: fmt.Errorf(`ent: validator failed for field "Remark.create_at": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.UserName(); ok {
		if err := remark.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "Remark.user_name": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.TargetName(); ok {
		if err := remark.TargetNameValidator(v); err != nil {
			return &ValidationError{Name: "target_name", err: fmt.Errorf(`ent: validator failed for field "Remark.target_name": %w`, err)}
		}
	}
	return nil
}

func (ruo *RemarkUpdateOne) sqlSave(ctx context.Context) (_node *Remark, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(remark.Table, remark.Columns, sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Remark.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, remark.FieldID)
		for _, f := range fields {
			if !remark.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != remark.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.BlogID(); ok {
		_spec.SetField(remark.FieldBlogID, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.AddedBlogID(); ok {
		_spec.AddField(remark.FieldBlogID, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.IsReply(); ok {
		_spec.SetField(remark.FieldIsReply, field.TypeBool, value)
	}
	if value, ok := ruo.mutation.TargetID(); ok {
		_spec.SetField(remark.FieldTargetID, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Content(); ok {
		_spec.SetField(remark.FieldContent, field.TypeString, value)
	}
	if value, ok := ruo.mutation.CreateAt(); ok {
		_spec.SetField(remark.FieldCreateAt, field.TypeString, value)
	}
	if value, ok := ruo.mutation.IfDel(); ok {
		_spec.SetField(remark.FieldIfDel, field.TypeBool, value)
	}
	if value, ok := ruo.mutation.UserName(); ok {
		_spec.SetField(remark.FieldUserName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.TargetName(); ok {
		_spec.SetField(remark.FieldTargetName, field.TypeString, value)
	}
	if ruo.mutation.BlogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   remark.BlogsTable,
			Columns: []string{remark.BlogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.BlogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   remark.BlogsTable,
			Columns: []string{remark.BlogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Remark{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
