// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/blog"
	"server/ent/remark"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Remark is the model entity for the Remark schema.
type Remark struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// BlogID holds the value of the "blog_id" field.
	BlogID int `json:"blog_id,omitempty"`
	// IsReply holds the value of the "is_reply" field.
	IsReply bool `json:"is_reply,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID string `json:"target_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// CreateAt holds the value of the "create_at" field.
	CreateAt string `json:"create_at,omitempty"`
	// IfDel holds the value of the "if_del" field.
	IfDel bool `json:"if_del,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName string `json:"user_name,omitempty"`
	// TargetName holds the value of the "target_name" field.
	TargetName string `json:"target_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RemarkQuery when eager-loading is set.
	Edges        RemarkEdges `json:"edges"`
	blog_remarks *int
	selectValues sql.SelectValues
}

// RemarkEdges holds the relations/edges for other nodes in the graph.
type RemarkEdges struct {
	// Blogs holds the value of the blogs edge.
	Blogs *Blog `json:"blogs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BlogsOrErr returns the Blogs value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RemarkEdges) BlogsOrErr() (*Blog, error) {
	if e.loadedTypes[0] {
		if e.Blogs == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: blog.Label}
		}
		return e.Blogs, nil
	}
	return nil, &NotLoadedError{edge: "blogs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Remark) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case remark.FieldIsReply, remark.FieldIfDel:
			values[i] = new(sql.NullBool)
		case remark.FieldID, remark.FieldBlogID:
			values[i] = new(sql.NullInt64)
		case remark.FieldTargetID, remark.FieldContent, remark.FieldCreateAt, remark.FieldUserName, remark.FieldTargetName:
			values[i] = new(sql.NullString)
		case remark.ForeignKeys[0]: // blog_remarks
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Remark fields.
func (r *Remark) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case remark.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case remark.FieldBlogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field blog_id", values[i])
			} else if value.Valid {
				r.BlogID = int(value.Int64)
			}
		case remark.FieldIsReply:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_reply", values[i])
			} else if value.Valid {
				r.IsReply = value.Bool
			}
		case remark.FieldTargetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				r.TargetID = value.String
			}
		case remark.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				r.Content = value.String
			}
		case remark.FieldCreateAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				r.CreateAt = value.String
			}
		case remark.FieldIfDel:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field if_del", values[i])
			} else if value.Valid {
				r.IfDel = value.Bool
			}
		case remark.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				r.UserName = value.String
			}
		case remark.FieldTargetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_name", values[i])
			} else if value.Valid {
				r.TargetName = value.String
			}
		case remark.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field blog_remarks", value)
			} else if value.Valid {
				r.blog_remarks = new(int)
				*r.blog_remarks = int(value.Int64)
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Remark.
// This includes values selected through modifiers, order, etc.
func (r *Remark) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryBlogs queries the "blogs" edge of the Remark entity.
func (r *Remark) QueryBlogs() *BlogQuery {
	return NewRemarkClient(r.config).QueryBlogs(r)
}

// Update returns a builder for updating this Remark.
// Note that you need to call Remark.Unwrap() before calling this method if this Remark
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Remark) Update() *RemarkUpdateOne {
	return NewRemarkClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Remark entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Remark) Unwrap() *Remark {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Remark is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Remark) String() string {
	var builder strings.Builder
	builder.WriteString("Remark(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("blog_id=")
	builder.WriteString(fmt.Sprintf("%v", r.BlogID))
	builder.WriteString(", ")
	builder.WriteString("is_reply=")
	builder.WriteString(fmt.Sprintf("%v", r.IsReply))
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(r.TargetID)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(r.Content)
	builder.WriteString(", ")
	builder.WriteString("create_at=")
	builder.WriteString(r.CreateAt)
	builder.WriteString(", ")
	builder.WriteString("if_del=")
	builder.WriteString(fmt.Sprintf("%v", r.IfDel))
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(r.UserName)
	builder.WriteString(", ")
	builder.WriteString("target_name=")
	builder.WriteString(r.TargetName)
	builder.WriteByte(')')
	return builder.String()
}

// Remarks is a parsable slice of Remark.
type Remarks []*Remark
