// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/blog"
	"server/ent/predicate"
	"server/ent/remark"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RemarkQuery is the builder for querying Remark entities.
type RemarkQuery struct {
	config
	ctx        *QueryContext
	order      []remark.OrderOption
	inters     []Interceptor
	predicates []predicate.Remark
	withBlogs  *BlogQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RemarkQuery builder.
func (rq *RemarkQuery) Where(ps ...predicate.Remark) *RemarkQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *RemarkQuery) Limit(limit int) *RemarkQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *RemarkQuery) Offset(offset int) *RemarkQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *RemarkQuery) Unique(unique bool) *RemarkQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *RemarkQuery) Order(o ...remark.OrderOption) *RemarkQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryBlogs chains the current query on the "blogs" edge.
func (rq *RemarkQuery) QueryBlogs() *BlogQuery {
	query := (&BlogClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(remark.Table, remark.FieldID, selector),
			sqlgraph.To(blog.Table, blog.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, remark.BlogsTable, remark.BlogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Remark entity from the query.
// Returns a *NotFoundError when no Remark was found.
func (rq *RemarkQuery) First(ctx context.Context) (*Remark, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{remark.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *RemarkQuery) FirstX(ctx context.Context) *Remark {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Remark ID from the query.
// Returns a *NotFoundError when no Remark ID was found.
func (rq *RemarkQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{remark.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *RemarkQuery) FirstIDX(ctx context.Context) int {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Remark entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Remark entity is found.
// Returns a *NotFoundError when no Remark entities are found.
func (rq *RemarkQuery) Only(ctx context.Context) (*Remark, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{remark.Label}
	default:
		return nil, &NotSingularError{remark.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *RemarkQuery) OnlyX(ctx context.Context) *Remark {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Remark ID in the query.
// Returns a *NotSingularError when more than one Remark ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *RemarkQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{remark.Label}
	default:
		err = &NotSingularError{remark.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *RemarkQuery) OnlyIDX(ctx context.Context) int {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Remarks.
func (rq *RemarkQuery) All(ctx context.Context) ([]*Remark, error) {
	ctx = setContextOp(ctx, rq.ctx, "All")
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Remark, *RemarkQuery]()
	return withInterceptors[[]*Remark](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *RemarkQuery) AllX(ctx context.Context) []*Remark {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Remark IDs.
func (rq *RemarkQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, "IDs")
	if err = rq.Select(remark.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *RemarkQuery) IDsX(ctx context.Context) []int {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *RemarkQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, "Count")
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*RemarkQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *RemarkQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *RemarkQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, "Exist")
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *RemarkQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RemarkQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *RemarkQuery) Clone() *RemarkQuery {
	if rq == nil {
		return nil
	}
	return &RemarkQuery{
		config:     rq.config,
		ctx:        rq.ctx.Clone(),
		order:      append([]remark.OrderOption{}, rq.order...),
		inters:     append([]Interceptor{}, rq.inters...),
		predicates: append([]predicate.Remark{}, rq.predicates...),
		withBlogs:  rq.withBlogs.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithBlogs tells the query-builder to eager-load the nodes that are connected to
// the "blogs" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RemarkQuery) WithBlogs(opts ...func(*BlogQuery)) *RemarkQuery {
	query := (&BlogClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withBlogs = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BlogID int `json:"blog_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Remark.Query().
//		GroupBy(remark.FieldBlogID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *RemarkQuery) GroupBy(field string, fields ...string) *RemarkGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RemarkGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = remark.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BlogID int `json:"blog_id,omitempty"`
//	}
//
//	client.Remark.Query().
//		Select(remark.FieldBlogID).
//		Scan(ctx, &v)
func (rq *RemarkQuery) Select(fields ...string) *RemarkSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &RemarkSelect{RemarkQuery: rq}
	sbuild.label = remark.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RemarkSelect configured with the given aggregations.
func (rq *RemarkQuery) Aggregate(fns ...AggregateFunc) *RemarkSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *RemarkQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !remark.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *RemarkQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Remark, error) {
	var (
		nodes       = []*Remark{}
		withFKs     = rq.withFKs
		_spec       = rq.querySpec()
		loadedTypes = [1]bool{
			rq.withBlogs != nil,
		}
	)
	if rq.withBlogs != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, remark.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Remark).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Remark{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withBlogs; query != nil {
		if err := rq.loadBlogs(ctx, query, nodes, nil,
			func(n *Remark, e *Blog) { n.Edges.Blogs = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *RemarkQuery) loadBlogs(ctx context.Context, query *BlogQuery, nodes []*Remark, init func(*Remark), assign func(*Remark, *Blog)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Remark)
	for i := range nodes {
		if nodes[i].blog_remarks == nil {
			continue
		}
		fk := *nodes[i].blog_remarks
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(blog.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "blog_remarks" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rq *RemarkQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *RemarkQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(remark.Table, remark.Columns, sqlgraph.NewFieldSpec(remark.FieldID, field.TypeInt))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, remark.FieldID)
		for i := range fields {
			if fields[i] != remark.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *RemarkQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(remark.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = remark.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RemarkGroupBy is the group-by builder for Remark entities.
type RemarkGroupBy struct {
	selector
	build *RemarkQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *RemarkGroupBy) Aggregate(fns ...AggregateFunc) *RemarkGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *RemarkGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, "GroupBy")
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RemarkQuery, *RemarkGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *RemarkGroupBy) sqlScan(ctx context.Context, root *RemarkQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RemarkSelect is the builder for selecting fields of Remark entities.
type RemarkSelect struct {
	*RemarkQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *RemarkSelect) Aggregate(fns ...AggregateFunc) *RemarkSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *RemarkSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, "Select")
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RemarkQuery, *RemarkSelect](ctx, rs.RemarkQuery, rs, rs.inters, v)
}

func (rs *RemarkSelect) sqlScan(ctx context.Context, root *RemarkQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
