// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/blog"
	"server/ent/remark"
	"server/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blogFields := schema.Blog{}.Fields()
	_ = blogFields
	// blogDescTitle is the schema descriptor for title field.
	blogDescTitle := blogFields[0].Descriptor()
	// blog.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	blog.TitleValidator = blogDescTitle.Validators[0].(func(string) error)
	// blogDescSubtitle is the schema descriptor for subtitle field.
	blogDescSubtitle := blogFields[1].Descriptor()
	// blog.SubtitleValidator is a validator for the "subtitle" field. It is called by the builders before save.
	blog.SubtitleValidator = blogDescSubtitle.Validators[0].(func(string) error)
	// blogDescTime is the schema descriptor for time field.
	blogDescTime := blogFields[2].Descriptor()
	// blog.DefaultTime holds the default value on creation for the time field.
	blog.DefaultTime = blogDescTime.Default.(string)
	// blogDescHits is the schema descriptor for hits field.
	blogDescHits := blogFields[4].Descriptor()
	// blog.HitsValidator is a validator for the "hits" field. It is called by the builders before save.
	blog.HitsValidator = blogDescHits.Validators[0].(func(int) error)
	// blogDescContentURL is the schema descriptor for content_url field.
	blogDescContentURL := blogFields[5].Descriptor()
	// blog.ContentURLValidator is a validator for the "content_url" field. It is called by the builders before save.
	blog.ContentURLValidator = blogDescContentURL.Validators[0].(func(string) error)
	remarkFields := schema.Remark{}.Fields()
	_ = remarkFields
	// remarkDescIsReply is the schema descriptor for is_reply field.
	remarkDescIsReply := remarkFields[1].Descriptor()
	// remark.DefaultIsReply holds the default value on creation for the is_reply field.
	remark.DefaultIsReply = remarkDescIsReply.Default.(bool)
	// remarkDescContent is the schema descriptor for content field.
	remarkDescContent := remarkFields[3].Descriptor()
	// remark.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	remark.ContentValidator = remarkDescContent.Validators[0].(func(string) error)
	// remarkDescCreateAt is the schema descriptor for create_at field.
	remarkDescCreateAt := remarkFields[4].Descriptor()
	// remark.CreateAtValidator is a validator for the "create_at" field. It is called by the builders before save.
	remark.CreateAtValidator = remarkDescCreateAt.Validators[0].(func(string) error)
	// remarkDescIfDel is the schema descriptor for if_del field.
	remarkDescIfDel := remarkFields[5].Descriptor()
	// remark.DefaultIfDel holds the default value on creation for the if_del field.
	remark.DefaultIfDel = remarkDescIfDel.Default.(bool)
	// remarkDescUserName is the schema descriptor for user_name field.
	remarkDescUserName := remarkFields[6].Descriptor()
	// remark.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	remark.UserNameValidator = remarkDescUserName.Validators[0].(func(string) error)
	// remarkDescTargetName is the schema descriptor for target_name field.
	remarkDescTargetName := remarkFields[7].Descriptor()
	// remark.TargetNameValidator is a validator for the "target_name" field. It is called by the builders before save.
	remark.TargetNameValidator = remarkDescTargetName.Validators[0].(func(string) error)
}
