version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
        - 9000:9000 
    network_mode: "host"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 3000:3000
    network_mode: "host"