// Code generated by ent, DO NOT EDIT.

package blog

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the blog type in the database.
	Label = "blog"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSubtitle holds the string denoting the subtitle field in the database.
	FieldSubtitle = "subtitle"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldCover holds the string denoting the cover field in the database.
	FieldCover = "cover"
	// FieldHits holds the string denoting the hits field in the database.
	FieldHits = "hits"
	// FieldContentURL holds the string denoting the content_url field in the database.
	FieldContentURL = "content_url"
	// EdgeRemarks holds the string denoting the remarks edge name in mutations.
	EdgeRemarks = "remarks"
	// Table holds the table name of the blog in the database.
	Table = "blogs"
	// RemarksTable is the table that holds the remarks relation/edge.
	RemarksTable = "remarks"
	// RemarksInverseTable is the table name for the Remark entity.
	// It exists in this package in order to avoid circular dependency with the "remark" package.
	RemarksInverseTable = "remarks"
	// RemarksColumn is the table column denoting the remarks relation/edge.
	RemarksColumn = "blog_remarks"
)

// Columns holds all SQL columns for blog fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldSubtitle,
	FieldTime,
	FieldCover,
	FieldHits,
	FieldContentURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// SubtitleValidator is a validator for the "subtitle" field. It is called by the builders before save.
	SubtitleValidator func(string) error
	// DefaultTime holds the default value on creation for the "time" field.
	DefaultTime string
	// HitsValidator is a validator for the "hits" field. It is called by the builders before save.
	HitsValidator func(int) error
	// ContentURLValidator is a validator for the "content_url" field. It is called by the builders before save.
	ContentURLValidator func(string) error
)

// OrderOption defines the ordering options for the Blog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySubtitle orders the results by the subtitle field.
func BySubtitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubtitle, opts...).ToFunc()
}

// ByTime orders the results by the time field.
func ByTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTime, opts...).ToFunc()
}

// ByCover orders the results by the cover field.
func ByCover(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCover, opts...).ToFunc()
}

// ByHits orders the results by the hits field.
func ByHits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHits, opts...).ToFunc()
}

// ByContentURL orders the results by the content_url field.
func ByContentURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentURL, opts...).ToFunc()
}

// ByRemarksCount orders the results by remarks count.
func ByRemarksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRemarksStep(), opts...)
	}
}

// ByRemarks orders the results by remarks terms.
func ByRemarks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRemarksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRemarksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RemarksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RemarksTable, RemarksColumn),
	)
}
