// Code generated by ent, DO NOT EDIT.

package blog

import (
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Blog {
	return predicate.Blog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Blog {
	return predicate.Blog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Blog {
	return predicate.Blog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Blog {
	return predicate.Blog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Blog {
	return predicate.Blog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Blog {
	return predicate.Blog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Blog {
	return predicate.Blog(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldTitle, v))
}

// Subtitle applies equality check predicate on the "subtitle" field. It's identical to SubtitleEQ.
func Subtitle(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldSubtitle, v))
}

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldTime, v))
}

// Cover applies equality check predicate on the "cover" field. It's identical to CoverEQ.
func Cover(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldCover, v))
}

// Hits applies equality check predicate on the "hits" field. It's identical to HitsEQ.
func Hits(v int) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldHits, v))
}

// ContentURL applies equality check predicate on the "content_url" field. It's identical to ContentURLEQ.
func ContentURL(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldContentURL, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContainsFold(FieldTitle, v))
}

// SubtitleEQ applies the EQ predicate on the "subtitle" field.
func SubtitleEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldSubtitle, v))
}

// SubtitleNEQ applies the NEQ predicate on the "subtitle" field.
func SubtitleNEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldNEQ(FieldSubtitle, v))
}

// SubtitleIn applies the In predicate on the "subtitle" field.
func SubtitleIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldIn(FieldSubtitle, vs...))
}

// SubtitleNotIn applies the NotIn predicate on the "subtitle" field.
func SubtitleNotIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldNotIn(FieldSubtitle, vs...))
}

// SubtitleGT applies the GT predicate on the "subtitle" field.
func SubtitleGT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGT(FieldSubtitle, v))
}

// SubtitleGTE applies the GTE predicate on the "subtitle" field.
func SubtitleGTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGTE(FieldSubtitle, v))
}

// SubtitleLT applies the LT predicate on the "subtitle" field.
func SubtitleLT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLT(FieldSubtitle, v))
}

// SubtitleLTE applies the LTE predicate on the "subtitle" field.
func SubtitleLTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLTE(FieldSubtitle, v))
}

// SubtitleContains applies the Contains predicate on the "subtitle" field.
func SubtitleContains(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContains(FieldSubtitle, v))
}

// SubtitleHasPrefix applies the HasPrefix predicate on the "subtitle" field.
func SubtitleHasPrefix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasPrefix(FieldSubtitle, v))
}

// SubtitleHasSuffix applies the HasSuffix predicate on the "subtitle" field.
func SubtitleHasSuffix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasSuffix(FieldSubtitle, v))
}

// SubtitleEqualFold applies the EqualFold predicate on the "subtitle" field.
func SubtitleEqualFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEqualFold(FieldSubtitle, v))
}

// SubtitleContainsFold applies the ContainsFold predicate on the "subtitle" field.
func SubtitleContainsFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContainsFold(FieldSubtitle, v))
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLTE(FieldTime, v))
}

// TimeContains applies the Contains predicate on the "time" field.
func TimeContains(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContains(FieldTime, v))
}

// TimeHasPrefix applies the HasPrefix predicate on the "time" field.
func TimeHasPrefix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasPrefix(FieldTime, v))
}

// TimeHasSuffix applies the HasSuffix predicate on the "time" field.
func TimeHasSuffix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasSuffix(FieldTime, v))
}

// TimeEqualFold applies the EqualFold predicate on the "time" field.
func TimeEqualFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEqualFold(FieldTime, v))
}

// TimeContainsFold applies the ContainsFold predicate on the "time" field.
func TimeContainsFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContainsFold(FieldTime, v))
}

// CoverEQ applies the EQ predicate on the "cover" field.
func CoverEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldCover, v))
}

// CoverNEQ applies the NEQ predicate on the "cover" field.
func CoverNEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldNEQ(FieldCover, v))
}

// CoverIn applies the In predicate on the "cover" field.
func CoverIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldIn(FieldCover, vs...))
}

// CoverNotIn applies the NotIn predicate on the "cover" field.
func CoverNotIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldNotIn(FieldCover, vs...))
}

// CoverGT applies the GT predicate on the "cover" field.
func CoverGT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGT(FieldCover, v))
}

// CoverGTE applies the GTE predicate on the "cover" field.
func CoverGTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGTE(FieldCover, v))
}

// CoverLT applies the LT predicate on the "cover" field.
func CoverLT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLT(FieldCover, v))
}

// CoverLTE applies the LTE predicate on the "cover" field.
func CoverLTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLTE(FieldCover, v))
}

// CoverContains applies the Contains predicate on the "cover" field.
func CoverContains(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContains(FieldCover, v))
}

// CoverHasPrefix applies the HasPrefix predicate on the "cover" field.
func CoverHasPrefix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasPrefix(FieldCover, v))
}

// CoverHasSuffix applies the HasSuffix predicate on the "cover" field.
func CoverHasSuffix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasSuffix(FieldCover, v))
}

// CoverEqualFold applies the EqualFold predicate on the "cover" field.
func CoverEqualFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEqualFold(FieldCover, v))
}

// CoverContainsFold applies the ContainsFold predicate on the "cover" field.
func CoverContainsFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContainsFold(FieldCover, v))
}

// HitsEQ applies the EQ predicate on the "hits" field.
func HitsEQ(v int) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldHits, v))
}

// HitsNEQ applies the NEQ predicate on the "hits" field.
func HitsNEQ(v int) predicate.Blog {
	return predicate.Blog(sql.FieldNEQ(FieldHits, v))
}

// HitsIn applies the In predicate on the "hits" field.
func HitsIn(vs ...int) predicate.Blog {
	return predicate.Blog(sql.FieldIn(FieldHits, vs...))
}

// HitsNotIn applies the NotIn predicate on the "hits" field.
func HitsNotIn(vs ...int) predicate.Blog {
	return predicate.Blog(sql.FieldNotIn(FieldHits, vs...))
}

// HitsGT applies the GT predicate on the "hits" field.
func HitsGT(v int) predicate.Blog {
	return predicate.Blog(sql.FieldGT(FieldHits, v))
}

// HitsGTE applies the GTE predicate on the "hits" field.
func HitsGTE(v int) predicate.Blog {
	return predicate.Blog(sql.FieldGTE(FieldHits, v))
}

// HitsLT applies the LT predicate on the "hits" field.
func HitsLT(v int) predicate.Blog {
	return predicate.Blog(sql.FieldLT(FieldHits, v))
}

// HitsLTE applies the LTE predicate on the "hits" field.
func HitsLTE(v int) predicate.Blog {
	return predicate.Blog(sql.FieldLTE(FieldHits, v))
}

// ContentURLEQ applies the EQ predicate on the "content_url" field.
func ContentURLEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEQ(FieldContentURL, v))
}

// ContentURLNEQ applies the NEQ predicate on the "content_url" field.
func ContentURLNEQ(v string) predicate.Blog {
	return predicate.Blog(sql.FieldNEQ(FieldContentURL, v))
}

// ContentURLIn applies the In predicate on the "content_url" field.
func ContentURLIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldIn(FieldContentURL, vs...))
}

// ContentURLNotIn applies the NotIn predicate on the "content_url" field.
func ContentURLNotIn(vs ...string) predicate.Blog {
	return predicate.Blog(sql.FieldNotIn(FieldContentURL, vs...))
}

// ContentURLGT applies the GT predicate on the "content_url" field.
func ContentURLGT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGT(FieldContentURL, v))
}

// ContentURLGTE applies the GTE predicate on the "content_url" field.
func ContentURLGTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldGTE(FieldContentURL, v))
}

// ContentURLLT applies the LT predicate on the "content_url" field.
func ContentURLLT(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLT(FieldContentURL, v))
}

// ContentURLLTE applies the LTE predicate on the "content_url" field.
func ContentURLLTE(v string) predicate.Blog {
	return predicate.Blog(sql.FieldLTE(FieldContentURL, v))
}

// ContentURLContains applies the Contains predicate on the "content_url" field.
func ContentURLContains(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContains(FieldContentURL, v))
}

// ContentURLHasPrefix applies the HasPrefix predicate on the "content_url" field.
func ContentURLHasPrefix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasPrefix(FieldContentURL, v))
}

// ContentURLHasSuffix applies the HasSuffix predicate on the "content_url" field.
func ContentURLHasSuffix(v string) predicate.Blog {
	return predicate.Blog(sql.FieldHasSuffix(FieldContentURL, v))
}

// ContentURLEqualFold applies the EqualFold predicate on the "content_url" field.
func ContentURLEqualFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldEqualFold(FieldContentURL, v))
}

// ContentURLContainsFold applies the ContainsFold predicate on the "content_url" field.
func ContentURLContainsFold(v string) predicate.Blog {
	return predicate.Blog(sql.FieldContainsFold(FieldContentURL, v))
}

// HasRemarks applies the HasEdge predicate on the "remarks" edge.
func HasRemarks() predicate.Blog {
	return predicate.Blog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RemarksTable, RemarksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRemarksWith applies the HasEdge predicate on the "remarks" edge with a given conditions (other predicates).
func HasRemarksWith(preds ...predicate.Remark) predicate.Blog {
	return predicate.Blog(func(s *sql.Selector) {
		step := newRemarksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Blog) predicate.Blog {
	return predicate.Blog(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Blog) predicate.Blog {
	return predicate.Blog(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Blog) predicate.Blog {
	return predicate.Blog(func(s *sql.Selector) {
		p(s.Not())
	})
}
