// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blog is the predicate function for blog builders.
type Blog func(*sql.Selector)

// Remark is the predicate function for remark builders.
type Remark func(*sql.Selector)
