// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlogsColumns holds the columns for the "blogs" table.
	BlogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "subtitle", Type: field.TypeString},
		{Name: "time", Type: field.TypeString, Default: "2023-07-31"},
		{Name: "cover", Type: field.TypeString},
		{Name: "hits", Type: field.TypeInt},
		{Name: "content_url", Type: field.TypeString},
	}
	// BlogsTable holds the schema information for the "blogs" table.
	BlogsTable = &schema.Table{
		Name:       "blogs",
		Columns:    BlogsColumns,
		PrimaryKey: []*schema.Column{BlogsColumns[0]},
	}
	// RemarksColumns holds the columns for the "remarks" table.
	RemarksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "blog_id", Type: field.TypeInt},
		{Name: "is_reply", Type: field.TypeBool, Default: false},
		{Name: "target_id", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "create_at", Type: field.TypeString},
		{Name: "if_del", Type: field.TypeBool, Default: false},
		{Name: "user_name", Type: field.TypeString},
		{Name: "target_name", Type: field.TypeString},
		{Name: "blog_remarks", Type: field.TypeInt, Nullable: true},
	}
	// RemarksTable holds the schema information for the "remarks" table.
	RemarksTable = &schema.Table{
		Name:       "remarks",
		Columns:    RemarksColumns,
		PrimaryKey: []*schema.Column{RemarksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "remarks_blogs_remarks",
				Columns:    []*schema.Column{RemarksColumns[9]},
				RefColumns: []*schema.Column{BlogsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlogsTable,
		RemarksTable,
	}
)

func init() {
	RemarksTable.ForeignKeys[0].RefTable = BlogsTable
}
