// Code generated by ent, DO NOT EDIT.

package remark

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the remark type in the database.
	Label = "remark"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlogID holds the string denoting the blog_id field in the database.
	FieldBlogID = "blog_id"
	// FieldIsReply holds the string denoting the is_reply field in the database.
	FieldIsReply = "is_reply"
	// FieldTargetID holds the string denoting the target_id field in the database.
	FieldTargetID = "target_id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldIfDel holds the string denoting the if_del field in the database.
	FieldIfDel = "if_del"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldTargetName holds the string denoting the target_name field in the database.
	FieldTargetName = "target_name"
	// EdgeBlogs holds the string denoting the blogs edge name in mutations.
	EdgeBlogs = "blogs"
	// Table holds the table name of the remark in the database.
	Table = "remarks"
	// BlogsTable is the table that holds the blogs relation/edge.
	BlogsTable = "remarks"
	// BlogsInverseTable is the table name for the Blog entity.
	// It exists in this package in order to avoid circular dependency with the "blog" package.
	BlogsInverseTable = "blogs"
	// BlogsColumn is the table column denoting the blogs relation/edge.
	BlogsColumn = "blog_remarks"
)

// Columns holds all SQL columns for remark fields.
var Columns = []string{
	FieldID,
	FieldBlogID,
	FieldIsReply,
	FieldTargetID,
	FieldContent,
	FieldCreateAt,
	FieldIfDel,
	FieldUserName,
	FieldTargetName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "remarks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"blog_remarks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsReply holds the default value on creation for the "is_reply" field.
	DefaultIsReply bool
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// CreateAtValidator is a validator for the "create_at" field. It is called by the builders before save.
	CreateAtValidator func(string) error
	// DefaultIfDel holds the default value on creation for the "if_del" field.
	DefaultIfDel bool
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// TargetNameValidator is a validator for the "target_name" field. It is called by the builders before save.
	TargetNameValidator func(string) error
)

// OrderOption defines the ordering options for the Remark queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBlogID orders the results by the blog_id field.
func ByBlogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlogID, opts...).ToFunc()
}

// ByIsReply orders the results by the is_reply field.
func ByIsReply(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsReply, opts...).ToFunc()
}

// ByTargetID orders the results by the target_id field.
func ByTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetID, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCreateAt orders the results by the create_at field.
func ByCreateAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateAt, opts...).ToFunc()
}

// ByIfDel orders the results by the if_del field.
func ByIfDel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIfDel, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByTargetName orders the results by the target_name field.
func ByTargetName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetName, opts...).ToFunc()
}

// ByBlogsField orders the results by blogs field.
func ByBlogsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlogsStep(), sql.OrderByField(field, opts...))
	}
}
func newBlogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BlogsTable, BlogsColumn),
	)
}
