// Code generated by ent, DO NOT EDIT.

package remark

import (
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Remark {
	return predicate.Remark(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Remark {
	return predicate.Remark(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Remark {
	return predicate.Remark(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Remark {
	return predicate.Remark(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Remark {
	return predicate.Remark(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Remark {
	return predicate.Remark(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Remark {
	return predicate.Remark(sql.FieldLTE(FieldID, id))
}

// BlogID applies equality check predicate on the "blog_id" field. It's identical to BlogIDEQ.
func BlogID(v int) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldBlogID, v))
}

// IsReply applies equality check predicate on the "is_reply" field. It's identical to IsReplyEQ.
func IsReply(v bool) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldIsReply, v))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldTargetID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldContent, v))
}

// CreateAt applies equality check predicate on the "create_at" field. It's identical to CreateAtEQ.
func CreateAt(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldCreateAt, v))
}

// IfDel applies equality check predicate on the "if_del" field. It's identical to IfDelEQ.
func IfDel(v bool) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldIfDel, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldUserName, v))
}

// TargetName applies equality check predicate on the "target_name" field. It's identical to TargetNameEQ.
func TargetName(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldTargetName, v))
}

// BlogIDEQ applies the EQ predicate on the "blog_id" field.
func BlogIDEQ(v int) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldBlogID, v))
}

// BlogIDNEQ applies the NEQ predicate on the "blog_id" field.
func BlogIDNEQ(v int) predicate.Remark {
	return predicate.Remark(sql.FieldNEQ(FieldBlogID, v))
}

// BlogIDIn applies the In predicate on the "blog_id" field.
func BlogIDIn(vs ...int) predicate.Remark {
	return predicate.Remark(sql.FieldIn(FieldBlogID, vs...))
}

// BlogIDNotIn applies the NotIn predicate on the "blog_id" field.
func BlogIDNotIn(vs ...int) predicate.Remark {
	return predicate.Remark(sql.FieldNotIn(FieldBlogID, vs...))
}

// BlogIDGT applies the GT predicate on the "blog_id" field.
func BlogIDGT(v int) predicate.Remark {
	return predicate.Remark(sql.FieldGT(FieldBlogID, v))
}

// BlogIDGTE applies the GTE predicate on the "blog_id" field.
func BlogIDGTE(v int) predicate.Remark {
	return predicate.Remark(sql.FieldGTE(FieldBlogID, v))
}

// BlogIDLT applies the LT predicate on the "blog_id" field.
func BlogIDLT(v int) predicate.Remark {
	return predicate.Remark(sql.FieldLT(FieldBlogID, v))
}

// BlogIDLTE applies the LTE predicate on the "blog_id" field.
func BlogIDLTE(v int) predicate.Remark {
	return predicate.Remark(sql.FieldLTE(FieldBlogID, v))
}

// IsReplyEQ applies the EQ predicate on the "is_reply" field.
func IsReplyEQ(v bool) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldIsReply, v))
}

// IsReplyNEQ applies the NEQ predicate on the "is_reply" field.
func IsReplyNEQ(v bool) predicate.Remark {
	return predicate.Remark(sql.FieldNEQ(FieldIsReply, v))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldNotIn(FieldTargetID, vs...))
}

// TargetIDGT applies the GT predicate on the "target_id" field.
func TargetIDGT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGT(FieldTargetID, v))
}

// TargetIDGTE applies the GTE predicate on the "target_id" field.
func TargetIDGTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGTE(FieldTargetID, v))
}

// TargetIDLT applies the LT predicate on the "target_id" field.
func TargetIDLT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLT(FieldTargetID, v))
}

// TargetIDLTE applies the LTE predicate on the "target_id" field.
func TargetIDLTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLTE(FieldTargetID, v))
}

// TargetIDContains applies the Contains predicate on the "target_id" field.
func TargetIDContains(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContains(FieldTargetID, v))
}

// TargetIDHasPrefix applies the HasPrefix predicate on the "target_id" field.
func TargetIDHasPrefix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasPrefix(FieldTargetID, v))
}

// TargetIDHasSuffix applies the HasSuffix predicate on the "target_id" field.
func TargetIDHasSuffix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasSuffix(FieldTargetID, v))
}

// TargetIDEqualFold applies the EqualFold predicate on the "target_id" field.
func TargetIDEqualFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEqualFold(FieldTargetID, v))
}

// TargetIDContainsFold applies the ContainsFold predicate on the "target_id" field.
func TargetIDContainsFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContainsFold(FieldTargetID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContainsFold(FieldContent, v))
}

// CreateAtEQ applies the EQ predicate on the "create_at" field.
func CreateAtEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldCreateAt, v))
}

// CreateAtNEQ applies the NEQ predicate on the "create_at" field.
func CreateAtNEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldNEQ(FieldCreateAt, v))
}

// CreateAtIn applies the In predicate on the "create_at" field.
func CreateAtIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldIn(FieldCreateAt, vs...))
}

// CreateAtNotIn applies the NotIn predicate on the "create_at" field.
func CreateAtNotIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldNotIn(FieldCreateAt, vs...))
}

// CreateAtGT applies the GT predicate on the "create_at" field.
func CreateAtGT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGT(FieldCreateAt, v))
}

// CreateAtGTE applies the GTE predicate on the "create_at" field.
func CreateAtGTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGTE(FieldCreateAt, v))
}

// CreateAtLT applies the LT predicate on the "create_at" field.
func CreateAtLT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLT(FieldCreateAt, v))
}

// CreateAtLTE applies the LTE predicate on the "create_at" field.
func CreateAtLTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLTE(FieldCreateAt, v))
}

// CreateAtContains applies the Contains predicate on the "create_at" field.
func CreateAtContains(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContains(FieldCreateAt, v))
}

// CreateAtHasPrefix applies the HasPrefix predicate on the "create_at" field.
func CreateAtHasPrefix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasPrefix(FieldCreateAt, v))
}

// CreateAtHasSuffix applies the HasSuffix predicate on the "create_at" field.
func CreateAtHasSuffix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasSuffix(FieldCreateAt, v))
}

// CreateAtEqualFold applies the EqualFold predicate on the "create_at" field.
func CreateAtEqualFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEqualFold(FieldCreateAt, v))
}

// CreateAtContainsFold applies the ContainsFold predicate on the "create_at" field.
func CreateAtContainsFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContainsFold(FieldCreateAt, v))
}

// IfDelEQ applies the EQ predicate on the "if_del" field.
func IfDelEQ(v bool) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldIfDel, v))
}

// IfDelNEQ applies the NEQ predicate on the "if_del" field.
func IfDelNEQ(v bool) predicate.Remark {
	return predicate.Remark(sql.FieldNEQ(FieldIfDel, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContainsFold(FieldUserName, v))
}

// TargetNameEQ applies the EQ predicate on the "target_name" field.
func TargetNameEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEQ(FieldTargetName, v))
}

// TargetNameNEQ applies the NEQ predicate on the "target_name" field.
func TargetNameNEQ(v string) predicate.Remark {
	return predicate.Remark(sql.FieldNEQ(FieldTargetName, v))
}

// TargetNameIn applies the In predicate on the "target_name" field.
func TargetNameIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldIn(FieldTargetName, vs...))
}

// TargetNameNotIn applies the NotIn predicate on the "target_name" field.
func TargetNameNotIn(vs ...string) predicate.Remark {
	return predicate.Remark(sql.FieldNotIn(FieldTargetName, vs...))
}

// TargetNameGT applies the GT predicate on the "target_name" field.
func TargetNameGT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGT(FieldTargetName, v))
}

// TargetNameGTE applies the GTE predicate on the "target_name" field.
func TargetNameGTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldGTE(FieldTargetName, v))
}

// TargetNameLT applies the LT predicate on the "target_name" field.
func TargetNameLT(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLT(FieldTargetName, v))
}

// TargetNameLTE applies the LTE predicate on the "target_name" field.
func TargetNameLTE(v string) predicate.Remark {
	return predicate.Remark(sql.FieldLTE(FieldTargetName, v))
}

// TargetNameContains applies the Contains predicate on the "target_name" field.
func TargetNameContains(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContains(FieldTargetName, v))
}

// TargetNameHasPrefix applies the HasPrefix predicate on the "target_name" field.
func TargetNameHasPrefix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasPrefix(FieldTargetName, v))
}

// TargetNameHasSuffix applies the HasSuffix predicate on the "target_name" field.
func TargetNameHasSuffix(v string) predicate.Remark {
	return predicate.Remark(sql.FieldHasSuffix(FieldTargetName, v))
}

// TargetNameEqualFold applies the EqualFold predicate on the "target_name" field.
func TargetNameEqualFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldEqualFold(FieldTargetName, v))
}

// TargetNameContainsFold applies the ContainsFold predicate on the "target_name" field.
func TargetNameContainsFold(v string) predicate.Remark {
	return predicate.Remark(sql.FieldContainsFold(FieldTargetName, v))
}

// HasBlogs applies the HasEdge predicate on the "blogs" edge.
func HasBlogs() predicate.Remark {
	return predicate.Remark(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BlogsTable, BlogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlogsWith applies the HasEdge predicate on the "blogs" edge with a given conditions (other predicates).
func HasBlogsWith(preds ...predicate.Blog) predicate.Remark {
	return predicate.Remark(func(s *sql.Selector) {
		step := newBlogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Remark) predicate.Remark {
	return predicate.Remark(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Remark) predicate.Remark {
	return predicate.Remark(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Remark) predicate.Remark {
	return predicate.Remark(func(s *sql.Selector) {
		p(s.Not())
	})
}
